# Generated by Django 2.1.1 on 2019-08-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_auto_20190809_2222'),
        ('review', '0019_auto_20190809_2027'),
    ]

    operations = [
    ]
